# Generated by Django 4.1.7 on 2026-03-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0009_contactinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='mobile_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='office_hours',
        ),
    ]
