# Generated by Django 4.1.7 on 2026-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0011_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='cv_url',
        ),
        migrations.AddField(
            model_name='developer',
            name='linked_in_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
