# Generated by Django 5.2.12 on 2026-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0012_remove_developer_cv_url_developer_linked_in_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
